### ISSUE TITLE
Server loses connection whenever map change

### ISSUE THREAD

**Issue by crashzk** [splewis/csgo-pug-setup#322]
### Expected behavior
Whenever you change maps do this without losing the server connection.

### Actual behavior
Currently when you finish a competitive and have the voting of maps, when you switch to the winning map the server loses the connection for a few seconds, comes back and then changes the map to the chosen one in the vote.

### Steps to reproduce
- Installation of PUGSetup;
- Play an entire competitive;
- Choose the next map in the vote PUGSetup;
- Done, just wait;

_**OBS:** Currently I don't have any map voting plugin, I use PUGSetup itself for this function. The only active plugin related to the map would be `nextmap.smx`._

### SM Plugins List
```
[SM] Listing 55 plugins:
  01 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceBans++ Dev Team
  02 "Nikooo777" (1.0) by Nikooo777
  03 "REGEX word filter" (1.2) by Twilight Suzuka
  04 "Console Say" (1.0.1) by abnerfs
  05 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBans++ Dev Team
  06 "[CS:GO] Music Kits [Menu]" (1.7.4) by iEx Edited by Kento
  07 "CS:GO PugSetup: team names setter" (2.0.6-dev+493) by splewis
  08 "Basic Info Triggers" (1.10.0.6477) by AlliedModders LLC
  09 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
  10 "Steam Works Group Manager" (1.9.1) by Someone
  11 "TecnoHard™ Dano Só Granadas" (1.5) by AbNeR @CSB
  12 "TecnoHard™ Plugins Block" (1.2) by AbNeR @CSB
  13 "CS:GO PugSetup: autokicker" (2.0.6-dev+493) by splewis
  14 "Player Commands" (1.10.0.6477) by AlliedModders LLC
  15 "CS:GO PugSetup: damage printer" (2.0.6-dev+493) by splewis
  16 "CS:GO PugSetup: hostname setter" (2.0.6-dev+493) by splewis
  17 "Simple Stealth" (1.0) by Potatoz
  18 "Client Preferences" (1.10.0.6477) by AlliedModders LLC
  19 "Smart Link Remover" (1.6.2) by Totenfluch, Mitch, Agent Wesker
  20 "Weapons & Knives" (1.5.0) by kgns | oyunhost.net
  21 "Basic Commands" (1.10.0.6477) by AlliedModders LLC
  22 "Fun Votes" (1.10.0.6477) by AlliedModders LLC
  23 "DR.API HIGH PING KICKER" (1.0.2) by Dr. Api
  24 "Gloves" (1.0.4) by kgns | oyunhost.net
  25 "[ ZK Servidores™ ] - Block Tag Groups Steam" (1.0.0) by Geison TecnoHard & crashzk
  26 "VAC Status Checker" (2.5.0) by StevoTVR
  27 "CS:GO PugSetup: write team money to chat" (2.0.6-dev+493) by Versatile_BFG/jkroepke
  28 "SourceBans++ Report Plugin" (1.6.3) by RumbleFrog, SourceBans++ Dev Team
  29 "Basic Votes" (1.10.0.6477) by AlliedModders LLC
  30 "TecnoHard Chat Tags" (1.5.7) by AbNeR @CSB
  31 "GameVoting" (1.9.1) by Neatek
  32 "SourceBans++: SourceSleuth" (1.6.3) by ecca, SourceBans++ Dev Team
  33 "Default SM Text Replacer" (1.0) by Bacardi & Mitch - Edited: Cruze
  34 "Admin Help" (1.10.0.6477) by AlliedModders LLC
  35 "Basic Comm Control" (1.10.0.6477) by AlliedModders LLC
  36 "Reserved Slots" (1.10.0.6477) by AlliedModders LLC
  37 "CS:GO PugSetup: team locker" (2.0.6-dev+493) by splewis
  38 "CS:GO PugSetup: RWS balancer" (2.0.6-dev+493) by splewis
  39 "ServerAdvertisements3" (3.1.3) by ESK0
  40 "SourceBans++: Bans Checker" (1.6.3) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  41 "Bad name kick / ban" (1.0.0) by 2NASTY4U
  42 "SourceTV / GOTV Protector" (1.0) by CrazyHackGUT aka Kruzya
  43 "[ ZK Servidores™ ] - Block Commands" (1.0.0) by Geison TecnoHard & crashzk
  44 "Admin Menu" (1.10.0.6477) by AlliedModders LLC
  45 "AFK Manager" (4.3.0) by Rothgar
  46 "[SWGM] Command Listener" (1.2.1) by Someone
  47 "NonPrimeKicker" (1.2) by Summer_Soldier
  48 "Nextmap" (1.10.0.6477) by AlliedModders LLC
  49 "CS:GO PugSetup" (2.0.6-dev+493) by splewis
  50 "Sound Commands" (1.10.0.6477) by AlliedModders LLC
  51 "Anti-Flood" (1.10.0.6477) by AlliedModders LLC
  52 "Fun Commands" (1.10.0.6477) by AlliedModders LLC
  53 "Basic Chat" (1.10.0.6477) by AlliedModders LLC
  54 "Admin File Reader" (1.10.0.6477) by AlliedModders LLC
  55 "SM Franug Valve Sprays" (1.5.3) by Franc1sco Steam: franug
```

### SM Exts List
```
[SM] Displaying 16 extensions:
[01] Automatic Updater (1.10.0.6477): Updates SourceMod gamedata files
[02] Webternet (1.10.0.6477): Extension for interacting with URLs
[03] CS Tools (1.10.0.6477): CS extended functionality
[04] BinTools (1.10.0.6477): Low-level C/C++ Calling API
[05] SDK Tools (1.10.0.6477): Source SDK Tools
[06] Top Menus (1.10.0.6477): Creates sorted nested menus
[07] Regex (1.10.0.6477): Provides regex natives for plugins
[08] SDK Hooks (1.10.0.6477): Source SDK Hooks
[09] Client Preferences (1.10.0.6477): Saves client preference settings
[10] SQLite (1.10.0.6477): SQLite Driver
[11] GeoIP (1.10.0.6477): Geographical IP information
[12] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[13] PTaH (1.1.1): Additional CS:GO Hooks and Natives
[14] <OPTIONAL> file "steamtools.ext.so": /home/ogp_agent/OGP_User_Files/whmcs/957/csgo/addons/sourcemod/extensions/steamtools.ext.so: cannot open shared object file: No such file or directory
[15] Socket (3.0.1): Socket extension for SourceMod
[16] MySQL-DBI (1.10.0.6477): MySQL driver implementation for DBI
```

- Plugin Version: CS:GO PugSetup (2.0.6-dev+493) by splewis
- SourceMod Version: 1.10.0.6477

### LOGS Errors
[errors_20200329.log](https://github.com/splewis/csgo-pug-setup/files/4399723/errors_20200329.log)
[L20200329.log](https://github.com/splewis/csgo-pug-setup/files/4399724/L20200329.log)

**Comment by crashzk** [comment]
Could it be how PUGSetup changes maps, a method he uses in this case.

**Comment by ConnorBP** [comment]
I'm getting the same issue. It is causing gotv demos to corrupt often cause the server crashes on map change before it can save the last round

**Comment by spacecow123** [comment]
Same problem here

**Comment by crashzk** [comment]
I made a video showing the BUG, ​​without any editing, kind of long to show everything.

https://vimeo.com/403901961

That would be the problem I have been suffering from.

**Comment by splewis** [comment]
It sounds like your server is crashing. Have you installed accelerator? Do you have any reason to this pugsetup is causing the crashes?

"Installation of PUGSetup;
Play an entire competitive;
Choose the next map in the vote PUGSetup;
Done, just wait;"

These, unfortunately, are not steps to reproduce. My server does not crash.

**Comment by crashzk** [comment]
@splewis I've been doing some more tests with other Competitive / Mix plugins, in the case of WarMod, the problem still occurs, I believe it is not connected to PUGSetup.

As far as I can see, the nextmap has moments that fail, it does not change the map, even if you have the map voting active on the server. I noticed that it only occurs with the standard voting plugins for SourceMod maps, I am testing with other voting plugins to see if it occurs.

Anyway, the problem is not related to PUGSetup, it is something related to the exchange of maps or even to the wrong configuration of `maplist.txt` or `mapcycle.txt`.

**Comment by spacecow123** [comment]
@crashzk is there somewhere else I can follow this problem along? Still trying to find a solution to it.

Thanks!

**Comment by crashzk** [comment]
> @crashzk is there somewhere else I can follow this problem along? Still trying to find a solution to it.
> 
> Thanks!

This BUG only happens on my Competitive servers, even using PUGSetup or WarMod.

Doing some tests I saw that it happens if I leave the default plug-in plugins for SourceMod's map enabled.

The solution I found that worked for me was to install a map voting plugin, other than the SourceMod standard.

Also check if your list of maps is configured correctly, the `maplist.txt` and `mapcycle.txt` files, if there are errors in it it can cause this failure as well.
